"""initial airport operations schema

Revision ID: d7989b52d0ce
Revises:
Create Date: 2026-07-15 14:39:32.939001

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "d7989b52d0ce"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Required by the gate_assignments exclusion constraint: GiST cannot index
    # plain integer equality (gate_id WITH =) until btree_gist is installed.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "airlines",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("iata_code", sa.String(length=3), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("contact_info", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(iata_code) BETWEEN 2 AND 3", name=op.f("ck_airlines_iata_code_length")
        ),
        sa.CheckConstraint(
            "iata_code = upper(iata_code)", name=op.f("ck_airlines_iata_code_uppercase")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_airlines")),
    )
    op.create_index(op.f("ix_airlines_iata_code"), "airlines", ["iata_code"], unique=True)
    op.create_table(
        "emergency_protocols",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "fire", "medical", "security", name="ck_emergencytype", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_emergency_protocols")),
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("department", sa.String(length=50), nullable=False),
        sa.Column("contact_info", sa.String(length=255), nullable=True),
        sa.Column("salary", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("salary >= 0", name=op.f("ck_employees_salary_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employees")),
    )
    op.create_index(op.f("ix_employees_department"), "employees", ["department"], unique=False)
    op.create_table(
        "fuel_stations",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("location", sa.String(length=50), nullable=False),
        sa.Column("capacity_litres", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "capacity_litres > 0", name=op.f("ck_fuel_stations_capacity_litres_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fuel_stations")),
    )
    op.create_table(
        "parking_lots",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("location", sa.String(length=50), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("available", "full", name="ck_parkingstatus", native_enum=False, length=32),
            server_default="available",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("capacity > 0", name=op.f("ck_parking_lots_capacity_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parking_lots")),
        sa.UniqueConstraint("location", name=op.f("uq_parking_lots_location")),
    )
    op.create_table(
        "passengers",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("passport_number", sa.String(length=20), nullable=False),
        sa.Column("nationality", sa.String(length=50), nullable=False),
        sa.Column("contact_info", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "date_of_birth < CURRENT_DATE", name=op.f("ck_passengers_date_of_birth_in_past")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passengers")),
    )
    op.create_index(op.f("ix_passengers_last_name"), "passengers", ["last_name"], unique=False)
    op.create_index(
        op.f("ix_passengers_passport_number"), "passengers", ["passport_number"], unique=True
    )
    op.create_table(
        "runways",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("runway_number", sa.String(length=10), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "available",
                "occupied",
                "maintenance",
                name="ck_runwaystatus",
                native_enum=False,
                length=32,
            ),
            server_default="available",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runways")),
        sa.UniqueConstraint("runway_number", name=op.f("uq_runways_runway_number")),
    )
    op.create_table(
        "taxi_services",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("driver_name", sa.String(length=100), nullable=False),
        sa.Column("license_no", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxi_services")),
        sa.UniqueConstraint("license_no", name=op.f("uq_taxi_services_license_no")),
    )
    op.create_table(
        "terminals",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "operational",
                "under_maintenance",
                name="ck_terminalstatus",
                native_enum=False,
                length=32,
            ),
            server_default="operational",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("capacity > 0", name=op.f("ck_terminals_capacity_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_terminals")),
        sa.UniqueConstraint("name", name=op.f("uq_terminals_name")),
    )
    op.create_table(
        "vip_lounges",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "closed", name="ck_loungestatus", native_enum=False, length=32),
            server_default="open",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("capacity > 0", name=op.f("ck_vip_lounges_capacity_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vip_lounges")),
        sa.UniqueConstraint("name", name=op.f("uq_vip_lounges_name")),
    )
    op.create_table(
        "weather_info",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("observed_date", sa.Date(), nullable=False),
        sa.Column("observed_time", sa.Time(), nullable=False),
        sa.Column(
            "conditions",
            sa.Enum(
                "sunny",
                "rainy",
                "stormy",
                "cloudy",
                name="ck_weathercondition",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_info")),
    )
    op.create_index(
        op.f("ix_weather_info_observed_date"), "weather_info", ["observed_date"], unique=False
    )
    op.create_table(
        "airline_staff",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("airline_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["airline_id"],
            ["airlines.id"],
            name=op.f("fk_airline_staff_airline_id_airlines"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_airline_staff")),
    )
    op.create_index(
        op.f("ix_airline_staff_airline_id"), "airline_staff", ["airline_id"], unique=False
    )
    op.create_table(
        "duty_free_purchases",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("passenger_id", sa.Integer(), nullable=False),
        sa.Column("item_name", sa.String(length=50), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_duty_free_purchases_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["passenger_id"],
            ["passengers.id"],
            name=op.f("fk_duty_free_purchases_passenger_id_passengers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_duty_free_purchases")),
    )
    op.create_index(
        op.f("ix_duty_free_purchases_passenger_id"),
        "duty_free_purchases",
        ["passenger_id"],
        unique=False,
    )
    op.create_table(
        "emergency_contacts",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("relation", sa.String(length=50), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("passenger_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["passenger_id"],
            ["passengers.id"],
            name=op.f("fk_emergency_contacts_passenger_id_passengers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_emergency_contacts")),
    )
    op.create_index(
        op.f("ix_emergency_contacts_passenger_id"),
        "emergency_contacts",
        ["passenger_id"],
        unique=False,
    )
    op.create_table(
        "flights",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("flight_number", sa.String(length=10), nullable=False),
        sa.Column("airline_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("destination", sa.String(length=100), nullable=False),
        sa.Column("departure_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("arrival_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "delayed",
                "boarding",
                "departed",
                "completed",
                "cancelled",
                name="ck_flightstatus",
                native_enum=False,
                length=32,
            ),
            server_default="scheduled",
            nullable=False,
        ),
        sa.Column("seat_capacity", sa.Integer(), server_default="180", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "arrival_time > departure_time", name=op.f("ck_flights_arrival_after_departure")
        ),
        sa.CheckConstraint("seat_capacity > 0", name=op.f("ck_flights_seat_capacity_positive")),
        sa.CheckConstraint(
            "source <> destination", name=op.f("ck_flights_source_differs_from_destination")
        ),
        sa.ForeignKeyConstraint(
            ["airline_id"],
            ["airlines.id"],
            name=op.f("fk_flights_airline_id_airlines"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flights")),
    )
    op.create_index(op.f("ix_flights_airline_id"), "flights", ["airline_id"], unique=False)
    op.create_index(op.f("ix_flights_departure_time"), "flights", ["departure_time"], unique=False)
    op.create_index(op.f("ix_flights_flight_number"), "flights", ["flight_number"], unique=True)
    op.create_index(op.f("ix_flights_status"), "flights", ["status"], unique=False)
    op.create_index(
        "ix_flights_status_departure_time", "flights", ["status", "departure_time"], unique=False
    )
    op.create_table(
        "gates",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("terminal_id", sa.Integer(), nullable=False),
        sa.Column("gate_number", sa.String(length=10), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "available",
                "occupied",
                "maintenance",
                name="ck_gatestatus",
                native_enum=False,
                length=32,
            ),
            server_default="available",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["terminal_id"],
            ["terminals.id"],
            name=op.f("fk_gates_terminal_id_terminals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gates")),
        sa.UniqueConstraint("terminal_id", "gate_number", name="uq_gates_terminal_id_gate_number"),
    )
    op.create_index(op.f("ix_gates_terminal_id"), "gates", ["terminal_id"], unique=False)
    op.create_table(
        "hotel_reservations",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("hotel_name", sa.String(length=100), nullable=False),
        sa.Column("check_in_date", sa.Date(), nullable=False),
        sa.Column("check_out_date", sa.Date(), nullable=False),
        sa.Column("passenger_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "check_out_date > check_in_date",
            name=op.f("ck_hotel_reservations_check_out_after_check_in"),
        ),
        sa.ForeignKeyConstraint(
            ["passenger_id"],
            ["passengers.id"],
            name=op.f("fk_hotel_reservations_passenger_id_passengers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotel_reservations")),
    )
    op.create_index(
        op.f("ix_hotel_reservations_passenger_id"),
        "hotel_reservations",
        ["passenger_id"],
        unique=False,
    )
    op.create_table(
        "lost_and_found",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("found_date", sa.Date(), nullable=False),
        sa.Column("claimed_by_passenger_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claimed_by_passenger_id"],
            ["passengers.id"],
            name=op.f("fk_lost_and_found_claimed_by_passenger_id_passengers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lost_and_found")),
    )
    op.create_index(
        op.f("ix_lost_and_found_claimed_by_passenger_id"),
        "lost_and_found",
        ["claimed_by_passenger_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lost_and_found_found_date"), "lost_and_found", ["found_date"], unique=False
    )
    op.create_table(
        "maintenance_schedule",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "runway",
                "aircraft",
                "gate",
                name="ck_maintenancetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_maintenance_schedule_employee_id_employees"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_schedule")),
    )
    op.create_index(
        op.f("ix_maintenance_schedule_employee_id"),
        "maintenance_schedule",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maintenance_schedule_scheduled_date"),
        "maintenance_schedule",
        ["scheduled_date"],
        unique=False,
    )
    op.create_table(
        "staff_users",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "admin",
                "ops",
                "checkin",
                "security",
                name="ck_staffrole",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("employee_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "position('@' in email) > 1", name=op.f("ck_staff_users_email_has_at_sign")
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_staff_users_employee_id_employees"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_users")),
    )
    op.create_index(op.f("ix_staff_users_email"), "staff_users", ["email"], unique=True)
    op.create_index(
        op.f("ix_staff_users_employee_id"), "staff_users", ["employee_id"], unique=False
    )
    op.create_table(
        "cargo",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("flight_id", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "loaded",
                "in_transit",
                "unloaded",
                name="ck_cargostatus",
                native_enum=False,
                length=32,
            ),
            server_default="loaded",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("weight_kg > 0", name=op.f("ck_cargo_weight_kg_positive")),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flights.id"],
            name=op.f("fk_cargo_flight_id_flights"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cargo")),
    )
    op.create_index(op.f("ix_cargo_flight_id"), "cargo", ["flight_id"], unique=False)
    op.create_table(
        "flight_crew_schedule",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("crew_member_id", sa.Integer(), nullable=False),
        sa.Column("flight_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "pilot", "co_pilot", "cabin_crew", name="ck_crewrole", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["crew_member_id"],
            ["employees.id"],
            name=op.f("fk_flight_crew_schedule_crew_member_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flights.id"],
            name=op.f("fk_flight_crew_schedule_flight_id_flights"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flight_crew_schedule")),
        sa.UniqueConstraint(
            "flight_id", "crew_member_id", name="uq_flight_crew_schedule_flight_id_crew_member_id"
        ),
    )
    op.create_index(
        op.f("ix_flight_crew_schedule_crew_member_id"),
        "flight_crew_schedule",
        ["crew_member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flight_crew_schedule_flight_id"),
        "flight_crew_schedule",
        ["flight_id"],
        unique=False,
    )
    op.create_table(
        "gate_assignments",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("gate_id", sa.Integer(), nullable=False),
        sa.Column("flight_id", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.column("gate_id"), "="),
            (sa.literal_column("tstzrange(starts_at, ends_at)"), "&&"),
            where=sa.text("cancelled_at IS NULL"),
            using="gist",
            name="gate_assignments_no_overlap",
        ),
        sa.CheckConstraint(
            "ends_at > starts_at", name=op.f("ck_gate_assignments_ends_after_starts")
        ),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flights.id"],
            name=op.f("fk_gate_assignments_flight_id_flights"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["gate_id"],
            ["gates.id"],
            name=op.f("fk_gate_assignments_gate_id_gates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gate_assignments")),
    )
    op.create_index(
        op.f("ix_gate_assignments_flight_id"), "gate_assignments", ["flight_id"], unique=False
    )
    op.create_index(
        op.f("ix_gate_assignments_gate_id"), "gate_assignments", ["gate_id"], unique=False
    )
    op.create_table(
        "immigration",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("passenger_id", sa.Integer(), nullable=False),
        sa.Column("flight_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                name="ck_immigrationstatus",
                native_enum=False,
                length=32,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'pending') = (processed_at IS NULL)",
            name=op.f("ck_immigration_processed_at_matches_status"),
        ),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flights.id"],
            name=op.f("fk_immigration_flight_id_flights"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["passenger_id"],
            ["passengers.id"],
            name=op.f("fk_immigration_passenger_id_passengers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_immigration")),
        sa.UniqueConstraint(
            "passenger_id", "flight_id", name="uq_immigration_passenger_id_flight_id"
        ),
    )
    op.create_index(op.f("ix_immigration_flight_id"), "immigration", ["flight_id"], unique=False)
    op.create_index(
        op.f("ix_immigration_passenger_id"), "immigration", ["passenger_id"], unique=False
    )
    op.create_index(op.f("ix_immigration_status"), "immigration", ["status"], unique=False)
    op.create_table(
        "security_checkpoints",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("location", sa.String(length=50), nullable=False),
        sa.Column("gate_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="ck_checkpointstatus", native_enum=False, length=32),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gate_id"],
            ["gates.id"],
            name=op.f("fk_security_checkpoints_gate_id_gates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_checkpoints")),
    )
    op.create_index(
        op.f("ix_security_checkpoints_gate_id"), "security_checkpoints", ["gate_id"], unique=False
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("flight_id", sa.Integer(), nullable=False),
        sa.Column("passenger_id", sa.Integer(), nullable=False),
        sa.Column("seat_number", sa.String(length=5), nullable=False),
        sa.Column(
            "ticket_class",
            sa.Enum(
                "economy", "business", "first", name="ck_ticketclass", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "booking_status",
            sa.Enum(
                "confirmed",
                "checked_in",
                "cancelled",
                name="ck_bookingstatus",
                native_enum=False,
                length=32,
            ),
            server_default="confirmed",
            nullable=False,
        ),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(booking_status = 'checked_in') = (checked_in_at IS NOT NULL)",
            name=op.f("ck_tickets_checked_in_at_matches_status"),
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_tickets_price_non_negative")),
        sa.CheckConstraint(
            "seat_number = upper(seat_number)", name=op.f("ck_tickets_seat_number_uppercase")
        ),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flights.id"],
            name=op.f("fk_tickets_flight_id_flights"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["passenger_id"],
            ["passengers.id"],
            name=op.f("fk_tickets_passenger_id_passengers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
    )
    op.create_index(op.f("ix_tickets_booking_status"), "tickets", ["booking_status"], unique=False)
    op.create_index(op.f("ix_tickets_flight_id"), "tickets", ["flight_id"], unique=False)
    op.create_index(op.f("ix_tickets_passenger_id"), "tickets", ["passenger_id"], unique=False)
    op.create_index(
        "uq_tickets_flight_seat_active",
        "tickets",
        ["flight_id", "seat_number"],
        unique=True,
        postgresql_where=sa.text("booking_status IN ('confirmed', 'checked_in')"),
    )
    op.create_table(
        "baggage",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("tag_number", sa.String(length=12), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "checked_in",
                "in_transit",
                "loaded",
                "delivered",
                "lost",
                name="ck_baggagestatus",
                native_enum=False,
                length=32,
            ),
            server_default="checked_in",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "weight_kg > 0 AND weight_kg <= 100", name=op.f("ck_baggage_weight_kg_within_limits")
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_baggage_ticket_id_tickets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_baggage")),
    )
    op.create_index(op.f("ix_baggage_status"), "baggage", ["status"], unique=False)
    op.create_index(op.f("ix_baggage_tag_number"), "baggage", ["tag_number"], unique=True)
    op.create_index(op.f("ix_baggage_ticket_id"), "baggage", ["ticket_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_baggage_ticket_id"), table_name="baggage")
    op.drop_index(op.f("ix_baggage_tag_number"), table_name="baggage")
    op.drop_index(op.f("ix_baggage_status"), table_name="baggage")
    op.drop_table("baggage")
    op.drop_index(
        "uq_tickets_flight_seat_active",
        table_name="tickets",
        postgresql_where=sa.text("booking_status IN ('confirmed', 'checked_in')"),
    )
    op.drop_index(op.f("ix_tickets_passenger_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_flight_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_booking_status"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_security_checkpoints_gate_id"), table_name="security_checkpoints")
    op.drop_table("security_checkpoints")
    op.drop_index(op.f("ix_immigration_status"), table_name="immigration")
    op.drop_index(op.f("ix_immigration_passenger_id"), table_name="immigration")
    op.drop_index(op.f("ix_immigration_flight_id"), table_name="immigration")
    op.drop_table("immigration")
    op.drop_index(op.f("ix_gate_assignments_gate_id"), table_name="gate_assignments")
    op.drop_index(op.f("ix_gate_assignments_flight_id"), table_name="gate_assignments")
    op.drop_table("gate_assignments")
    op.drop_index(op.f("ix_flight_crew_schedule_flight_id"), table_name="flight_crew_schedule")
    op.drop_index(op.f("ix_flight_crew_schedule_crew_member_id"), table_name="flight_crew_schedule")
    op.drop_table("flight_crew_schedule")
    op.drop_index(op.f("ix_cargo_flight_id"), table_name="cargo")
    op.drop_table("cargo")
    op.drop_index(op.f("ix_staff_users_employee_id"), table_name="staff_users")
    op.drop_index(op.f("ix_staff_users_email"), table_name="staff_users")
    op.drop_table("staff_users")
    op.drop_index(op.f("ix_maintenance_schedule_scheduled_date"), table_name="maintenance_schedule")
    op.drop_index(op.f("ix_maintenance_schedule_employee_id"), table_name="maintenance_schedule")
    op.drop_table("maintenance_schedule")
    op.drop_index(op.f("ix_lost_and_found_found_date"), table_name="lost_and_found")
    op.drop_index(op.f("ix_lost_and_found_claimed_by_passenger_id"), table_name="lost_and_found")
    op.drop_table("lost_and_found")
    op.drop_index(op.f("ix_hotel_reservations_passenger_id"), table_name="hotel_reservations")
    op.drop_table("hotel_reservations")
    op.drop_index(op.f("ix_gates_terminal_id"), table_name="gates")
    op.drop_table("gates")
    op.drop_index("ix_flights_status_departure_time", table_name="flights")
    op.drop_index(op.f("ix_flights_status"), table_name="flights")
    op.drop_index(op.f("ix_flights_flight_number"), table_name="flights")
    op.drop_index(op.f("ix_flights_departure_time"), table_name="flights")
    op.drop_index(op.f("ix_flights_airline_id"), table_name="flights")
    op.drop_table("flights")
    op.drop_index(op.f("ix_emergency_contacts_passenger_id"), table_name="emergency_contacts")
    op.drop_table("emergency_contacts")
    op.drop_index(op.f("ix_duty_free_purchases_passenger_id"), table_name="duty_free_purchases")
    op.drop_table("duty_free_purchases")
    op.drop_index(op.f("ix_airline_staff_airline_id"), table_name="airline_staff")
    op.drop_table("airline_staff")
    op.drop_index(op.f("ix_weather_info_observed_date"), table_name="weather_info")
    op.drop_table("weather_info")
    op.drop_table("vip_lounges")
    op.drop_table("terminals")
    op.drop_table("taxi_services")
    op.drop_table("runways")
    op.drop_index(op.f("ix_passengers_passport_number"), table_name="passengers")
    op.drop_index(op.f("ix_passengers_last_name"), table_name="passengers")
    op.drop_table("passengers")
    op.drop_table("parking_lots")
    op.drop_table("fuel_stations")
    op.drop_index(op.f("ix_employees_department"), table_name="employees")
    op.drop_table("employees")
    op.drop_table("emergency_protocols")
    op.drop_index(op.f("ix_airlines_iata_code"), table_name="airlines")
    op.drop_table("airlines")
    # ### end Alembic commands ###
